environment: podman
deployments:
  containers:
    image: localhost
    pullPolicy: IfNotPresent
  volumes:
    - alexbrasser-website-website
    - appfusion-dashboard-dashboard
    - automtr-browser-browser
