server {
    include /etc/nginx/includes/listen.conf;

    server_name website.appfusion.localhost website.appfusion.fedora-workstation website.appfusion.alexbrasser.com;

    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        resolver ${NGINX_LOCAL_RESOLVERS} valid=5s ipv6=off;
        resolver_timeout 2s;

        set $upstream appfusion-website-pod:3000;
        proxy_pass http://$upstream;
    }
}