server {
    include /etc/nginx/includes/listen.conf;

    server_name codium.workspace.localhost codium.workspace.fedora-workstation;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        proxy_pass http://workspace-codium-pod:3000;
    }
}
