server {
    include /etc/nginx/includes/listen.conf;

    server_name ollama.workspace.localhost ollama.workspace.fedora-workstation;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        resolver ${NGINX_LOCAL_RESOLVERS} valid=5s ipv6=off;
        resolver_timeout 2s;

        set $upstream workspace-ollama-pod:11434;
        proxy_pass http://$upstream;
    }
}
