server {
    include /etc/nginx/includes/listen.conf;

    server_name open-webui.workspace.localhost open-webui.workspace.fedora-workstation;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        proxy_pass http://workspace-open-webui-pod:8080;
    }
}
