server {
    include /etc/nginx/includes/listen.conf;

    server_name opencode.workspace.localhost opencode.workspace.fedora-workstation;

    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        resolver ${NGINX_LOCAL_RESOLVERS} valid=5s ipv6=off;
        resolver_timeout 2s;

        set $opencode workspace-opencode-pod:3000;
        proxy_pass http://$opencode;
    }
}
