server {
    include /etc/nginx/includes/listen.conf;

    server_name openclaw.workspace.localhost openclaw.workspace.fedora-workstation;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        resolver ${NGINX_LOCAL_RESOLVERS} valid=5s ipv6=off;
        resolver_timeout 2s;

        set $openclaw workspace-openclaw-pod:18789;
        proxy_pass http://$openclaw;
    }
}
