server {
    include /etc/nginx/includes/listen.conf;

    server_name opencode.workspace.localhost opencode.workspace.fedora-workstation;

    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        proxy_pass http://workspace-opencode-pod:3000;
    }
}