server {
    include /etc/nginx/includes/listen.conf;

    server_name redis-insight.workspace.localhost redis-insight.workspace.fedora-workstation;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        proxy_pass http://workspace-redis-insight-pod:5540;
    }
}
