{{ if has "ollama" .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ollama
  labels:
    app: {{ .Release.Name }}-ollama
spec:
  {{ if .Values.devmode }}
  strategy:
    type: Recreate
  {{ end }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ollama
  template:
    metadata:
      annotations:
      {{ if .Values.devmode }}
        rollme: {{ randAlphaNum 5 | quote }}
      {{ end }}
      labels:
        app: {{ .Release.Name }}-ollama
        deployment: {{ .Release.Name }}-ollama
    spec:
      containers:
        - name: ollama
          image: docker.io/ollama/ollama:rocm
          imagePullPolicy: {{ .Values.deployments.containers.pullPolicy }}
          # Required for GPU passthrough
          securityContext:
            privileged: true
          volumeMounts:
            - name: {{ .Release.Name }}-ollama-ollama
              mountPath: /root/.ollama
          resources:
            limits:
              amd.com/gpu: 1 # requesting 1 GPU
      volumes:
        - name: {{ .Release.Name }}-ollama-ollama
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-ollama-ollama
{{ end }}