server {
    include /etc/nginx/includes/listen.conf;

    server_name dbgate.workspace.localhost dbgate.workspace.fedora-workstation;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        proxy_pass http://workspace-dbgate-pod:3000;
    }
}
