server {
    include /etc/nginx/includes/listen.conf;

    server_name ollama.workspace.localhost ollama.workspace.fedora-workstation;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;

        proxy_pass http://workspace-ollama-pod:11434;
    }
}
