apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-codium
spec:
  selector:
    app: {{ .Release.Name }}-codium
  ports:
  - name: {{ .Release.Name }}-codium-tcp
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: {{ .Release.Name }}-codium-udp
    protocol: UDP
    port: 3000
    targetPort: 3000
