apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dbgate
spec:
  selector:
    app: {{ .Release.Name }}-dbgate
  ports:
  - name: {{ .Release.Name }}-dbgate-tcp
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: {{ .Release.Name }}-dbgate-udp
    protocol: UDP
    port: 3000
    targetPort: 3000
