kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-dbgate-dbgate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem