kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-codium
spec:
  host: codium.{{ .Release.Name }}.{{ .Release.Namespace }}.apps.sno.okd
  to:
    kind: Service
    name: {{ .Release.Name }}-codium
    weight: 100
  port:
    targetPort: {{ .Release.Name }}-codium-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
