kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-dbgate
spec:
  host: dbgate.{{ .Release.Name }}.{{ .Release.Namespace }}.apps.sno.okd
  to:
    kind: Service
    name: {{ .Release.Name }}-dbgate
    weight: 100
  port:
    targetPort: {{ .Release.Name }}-dbgate-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
