apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-codium
data:
  git: |
    [user]
    email = alexbrasser@gmail.com
    name = Alex Brasser

    [init]
    defaultBranch = main

    [safe]
    directory = *
  
  codium: |
    {
      "editor.fontFamily": "Fira Code Retina",
      "editor.fontLigatures": true,
      "editor.formatOnSave": true,
      "files.autoSave": "onWindowChange",
      "workbench.colorTheme": "Default Dark Modern",
      "workbench.startupEditor": "none",
      "redhat.telemetry.enabled": false,
      "workbench.panel.defaultLocation": "left",
      "explorer.confirmDragAndDrop": false,
      "explorer.compactFolders": false,
      "git.enableSmartCommit": true,
      "terminal.integrated.tabs.enabled": false,
      "window.commandCenter": false,
      "twinny.ollamaHostname": "workspace-ollama-pod"
    }