apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-codium
data:
  continue: |
  {
  "models": [
    {
      "title": "Deepseek-r1 32b",
      "provider": "ollama",
      "model": "deepseek-r1:32b",
      "apiBase": "http://workspace-ollama-pod:11434"
    },
    {
      "title": "Llama3.1 8B",
      "provider": "ollama",
      "model": "llama3.1:8b",
      "apiBase": "http://workspace-ollama-pod:11434"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Qwen2.5-Coder 1.5B",
    "provider": "ollama",
    "model": "qwen2.5-coder:1.5b-base",
    "apiBase": "http://workspace-ollama-pod:11434"
  },
  "embeddingsProvider": {
    "title": "Nomic Embed Text",
    "provider": "ollama",
    "model": "nomic-embed-text",
    "apiBase": "http://workspace-ollama-pod:11434"
  },
  "contextProviders": [
    {
      "name": "code",
      "params": {}
    },
    {
      "name": "docs",
      "params": {}
    },
    {
      "name": "diff",
      "params": {}
    },
    {
      "name": "terminal",
      "params": {}
    },
    {
      "name": "problems",
      "params": {}
    },
    {
      "name": "folder",
      "params": {}
    },
    {
      "name": "codebase",
      "params": {}
    }
  ],
  "slashCommands": [
    {
      "name": "share",
      "description": "Export the current chat session to markdown"
    },
    {
      "name": "cmd",
      "description": "Generate a shell command"
    },
    {
      "name": "commit",
      "description": "Generate a git commit message"
    }
  ]
  }
  git: |
    [user]
    email = alexbrasser@gmail.com
    name = Alex Brasser

    [init]
    defaultBranch = main

    [safe]
    directory = *
  
  codium: |
    {
      "editor.fontFamily": "Fira Code Retina",
      "editor.fontLigatures": true,
      "editor.formatOnSave": true,
      "editor.inlineSuggest.syntaxHighlightingEnabled": true,
      "files.autoSave": "onWindowChange",
      "workbench.colorTheme": "Default Dark Modern",
      "workbench.startupEditor": "none",
      "workbench.editor.enablePreview": false,
      "workbench.layoutControl.enabled": false,
      "redhat.telemetry.enabled": false,
      "workbench.panel.defaultLocation": "left",
      "explorer.confirmDragAndDrop": false,
      "explorer.compactFolders": false,
      "git.enableSmartCommit": true,
      "terminal.integrated.tabs.enabled": false,
      "window.commandCenter": false,
      "continue.telemetryEnabled": false,
      "errorLens.messageEnabled": true
    }