{{ if .Values.services.gateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gateway
data:
  nginx.conf: |
{{ .Files.Get "configs/gateway/nginx.conf" | nindent 4 }}
  listen.conf: |
{{ .Files.Get "configs/gateway/listen.conf" | nindent 4 }}
  proxy.conf: |
{{ .Files.Get "configs/gateway/proxy.conf" | nindent 4 }}
  ssl.conf: |
{{ .Files.Get "configs/gateway/ssl.conf" | nindent 4 }}

{{ if .Values.services.ant.enabled }}
  ant.conf: |
{{ .Files.Get "configs/gateway/ant.conf" | nindent 4 }}
{{ end }}
{{ if .Values.services.codium.enabled }}
  codium.conf: |
{{ .Files.Get "configs/gateway/codium.conf" | nindent 4 }}
{{ end }}
{{ if .Values.services.dbgate.enabled }}
  dbgate.conf: |
{{ .Files.Get "configs/gateway/dbgate.conf" | nindent 4 }}
{{ end }}
{{ if .Values.services.ollama.enabled }}
  ollama.conf: |
{{ .Files.Get "configs/gateway/ollama.conf" | nindent 4 }}
{{ end }}
{{ if (index .Values.services "open-webui").enabled }}
  open-webui.conf: |
{{ .Files.Get "configs/gateway/open-webui.conf" | nindent 4 }}
{{ end }}
{{ if .Values.services.openclaw.enabled }}
  openclaw.conf: |
{{ .Files.Get "configs/gateway/openclaw.conf" | nindent 4 }}
{{ end }}
{{ if .Values.services.opencode.enabled }}
  opencode.conf: |
{{ .Files.Get "configs/gateway/opencode.conf" | nindent 4 }}
{{ end }}
{{ if (index .Values.services "redis-insight").enabled }}
  redis-insight.conf: |
{{ .Files.Get "configs/gateway/redis-insight.conf" | nindent 4 }}
{{ end }}
{{ if (index .Values.services "scalar").enabled }}
  scalar.conf: |
{{ .Files.Get "configs/gateway/scalar.conf" | nindent 4 }}
{{ end }}
  
  default.conf: |
    server {
      include /etc/nginx/includes/listen.conf;

      server_name localhost fedora-workstation;

      include /etc/nginx/includes/ssl.conf;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
    }
{{ end }}
