{{ if .Values.services.gateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gateway
data:
  nginx.conf: |
{{ .Files.Get "configs/gateway/nginx.conf" | nindent 4 }}
  listen.conf: |
{{ .Files.Get "configs/gateway/listen.conf" | nindent 4 }}
  proxy.conf: |
{{ .Files.Get "configs/gateway/proxy.conf" | nindent 4 }}
  ssl.conf: |
{{ .Files.Get "configs/gateway/ssl.conf" | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gateway-templates
data:
{{ range $path, $_ := .Files.Glob "configs/gateway/templates/*.conf.template" }}
  {{ base $path }}: |
{{ $.Files.Get $path | nindent 4 }}
{{ end }}
{{ end }}
