{{ if .Values.services.opencode.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opencode
data:
  opencode.json: |
{{ .Files.Get "configs/opencode/opencode.json" | nindent 4 }}
{{ end }}
