deployments:
  containers:
    image: localhost
    pullPolicy: IfNotPresent
    # pullPolicy: Always
  volumes:

services:
  codium:
    enabled: true
    image: localhost/core:latest
  opencode:
    enabled: true
    image: localhost/core:latest
  gateway:
    enabled: true
    image: docker.io/nginx:latest
  openclaw:
    enabled: false
    image: localhost/core:latest
    proxyImage: docker.io/nginx:latest
  dbgate:
    enabled: false
    image: docker.io/dbgate/dbgate:latest
  redis-insight:
    enabled: false
    image: docker.io/redis/redisinsight:latest
  open-webui:
    enabled: false
    image: ghcr.io/open-webui/open-webui:main
  ollama:
    enabled: false
    image: docker.io/ollama/ollama:rocm
  figma:
    enabled: false
    image: docker.io/acuvity/mcp-server-figma:latest
