environment: podman
devmode: false
deployments:
  containers:
    image: localhost
    pullPolicy: IfNotPresent
    # pullPolicy: Always
  volumes:
services:
  - codium
  # - openclaw
  - opencode
  # - dbgate
  # - redis-insight
  # - open-webui
  # - ollama
  # - figma