{{ if .Values.services.dbgate.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dbgate
  labels:
    app: {{ .Release.Name }}-dbgate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dbgate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dbgate
    spec:
      {{ include "pod.securityContext" . | indent 6 }}
      initContainers:
        - name: copy
          image: {{ .Values.services.dbgate.image }}
          command: ["/bin/cp"]
          args: ["-r",
            "/home/dbgate-docker",
            "/mnt/{{ .Release.Name }}-dbgate-dbgate",
          ]
          volumeMounts:
            - name: {{ .Release.Name }}-dbgate-dbgate
              mountPath: /mnt/{{ .Release.Name }}-dbgate-dbgate
        - name: volume
          image: docker.io/busybox:latest
          command: ["/bin/mkdir"]
          args: ["-p",
            "/mnt/{{ .Release.Name }}-dbgate-dbgate/.dbgate",
          ]
          volumeMounts:
            - name: {{ .Release.Name }}-dbgate-dbgate
              mountPath: /mnt/{{ .Release.Name }}-dbgate-dbgate
      containers:
        - name: dbgate
          {{ include "container.securityContext" . | indent 10 }}
          image: {{ .Values.services.dbgate.image }}
          imagePullPolicy: {{ .Values.deployments.containers.pullPolicy }}
          volumeMounts:
            - name: {{ .Release.Name }}-dbgate-dbgate
              mountPath: /home/dbgate-docker
              subPath: dbgate-docker
            - name: {{ .Release.Name }}-dbgate-dbgate
              mountPath: /.dbgate
              subPath: .dbgate
          # Example configuration for adding database sources
          # env:
          #   - name: CONNECTIONS
          #     value: database,cache

          #   - name: LABEL_database
          #     value: example-database
          #   - name: SERVER_database
          #     value: example-database-pod
          #   - name: PORT_database
          #     value: 5432
          #   - name: USER_database
          #     value: example
          #   - name: PASSWORD_database
          #     value: example
          #   - name: DATABASE_database
          #     value: example
          #   - name: ENGINE_database
          #     value: postgres@dbgate-plugin-postgres

          #   - name: LABEL_cache
          #     value: example-cache
          #   - name: SERVER_cache
          #     value: example-cache-pod
          #   - name: ENGINE_cache
          #     value: redis@dbgate-plugin-redis
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
      volumes:       
        - name: {{ .Release.Name }}-dbgate-dbgate
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-dbgate-dbgate
{{ end }}
