{{ if .Values.services.figma.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-figma
  labels:
    app: {{ .Release.Name }}-figma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-figma
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-figma
    spec:
      {{ include "pod.securityContext" . | indent 6 }}
      containers:
        - name: mcp
          image: {{ .Values.services.figma.image }}
          {{ include "container.securityContext" . | indent 10 }}
          imagePullPolicy: {{ .Values.deployments.containers.pullPolicy }}
          env:
            - name: FIGMA_API_KEY
              value: figd_something
{{ end }}
