{{ if has "figma" .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-figma
  labels:
    app: {{ .Release.Name }}-figma
spec:
  {{ if .Values.devmode }}
  strategy:
    type: Recreate
  {{ end }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-figma
  template:
    metadata:
      annotations:
      {{ if .Values.devmode }}
        rollme: {{ randAlphaNum 5 | quote }}
      {{ end }}
      labels:
        app: {{ .Release.Name }}-figma
        deployment: {{ .Release.Name }}-figma
    spec:
      {{ include "pod.securityContext" . | indent 6 }}
      containers:
        - name: mcp
          image: docker.io/acuvity/mcp-server-figma:latest
          {{ include "container.securityContext" . | indent 10 }}
          imagePullPolicy: {{ .Values.deployments.containers.pullPolicy }}
          env:
            - name: FIGMA_API_KEY
              value: figd_something
{{ end }}