{{ if .Values.services.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app: {{ .Release.Name }}-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-gateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-gateway
    spec:
      {{ include "pod.securityContext" . | indent 6 }}
      initContainers:
        - name: rm
          {{ include "container.securityContext" . | indent 10 }}
          image: docker.io/busybox:latest
          command: ["/bin/rm"]
          args: ["-rf",
            "/mnt/{{ .Release.Name }}-gateway-nginx/conf.d",
          ]
          volumeMounts:
            - name: {{ .Release.Name }}-gateway-nginx
              mountPath: /mnt/{{ .Release.Name }}-gateway-nginx
        - name: volume
          {{ include "container.securityContext" . | indent 10 }}
          image: docker.io/busybox:latest
          command: ["/bin/mkdir"]
          args: ["-p",
            "/mnt/{{ .Release.Name }}-gateway-nginx/nginx",
            "/mnt/{{ .Release.Name }}-gateway-nginx/run",
            "/mnt/{{ .Release.Name }}-gateway-nginx/conf.d",
          ]
          volumeMounts:
            - name: {{ .Release.Name }}-gateway-nginx
              mountPath: /mnt/{{ .Release.Name }}-gateway-nginx
      containers:
        - name: proxy
          {{ include "container.securityContext" . | indent 10 }}
          image: {{ .Values.services.gateway.image }}
          imagePullPolicy: {{ .Values.deployments.containers.pullPolicy }}
          env:
            - name: NGINX_ENTRYPOINT_LOCAL_RESOLVERS
              value: "1"
          ports:
            - containerPort: 8080
              hostPort: 8080
            - containerPort: 8443
              hostPort: 8443
          volumeMounts:
            - name: {{ .Release.Name }}-gateway-nginx
              mountPath: /var/cache/nginx
              subPath: nginx
            - name: {{ .Release.Name }}-gateway-nginx
              mountPath: /var/run
              subPath: run
            - name: {{ .Release.Name }}-gateway-nginx
              mountPath: /etc/nginx/conf.d
              subPath: conf.d
            - name: {{ .Release.Name }}-gateway-secret
              mountPath: /etc/nginx/certificates

            - name: {{ .Release.Name }}-gateway-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

            - name: {{ .Release.Name }}-gateway-includes
              mountPath: /etc/nginx/includes
            - name: {{ .Release.Name }}-gateway-templates
              mountPath: /etc/nginx/templates
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080

        - name: tunnel
          {{ include "container.securityContext" . | indent 10 }}
          image: docker.io/jnovack/autossh:latest
          env:
            - name: SSH_AUTH_SOCK
              value: /run/sshd.sock
          command:
            - autossh
            - "-M"
            - "0"
            - "-N"
            - "-o"
            - "UserKnownHostsFile=/dev/null"
            - "-o"
            - "StrictHostKeyChecking=no"
            # - "-L"
            # - "0.0.0.0:9222:127.0.0.1:9222"
            - "alexstorm13@host.containers.internal"

          volumeMounts:
            - name: sshd.sock
              mountPath: /run/sshd.sock
              readOnly: true

      volumes:
        - name: {{ .Release.Name }}-gateway-secret
          secret:
            secretName: {{ .Release.Name }}-gateway
            items:
              - key: tls.crt
                path: certificate.crt
              - key: tls.key
                path: private.key

        - name: {{ .Release.Name }}-gateway-config
          configMap:
            name: {{ .Release.Name }}-gateway
            optional: true

        - name: {{ .Release.Name }}-gateway-includes
          configMap:
            name: {{ .Release.Name }}-gateway
            optional: true
            items:
              - key: listen.conf
                path: listen.conf
              - key: proxy.conf
                path: proxy.conf
              - key: ssl.conf
                path: ssl.conf
        - name: {{ .Release.Name }}-gateway-templates
          configMap:
            name: {{ .Release.Name }}-gateway
            optional: true
            items:
              - key: default.conf
                path: default.conf.template
              {{ if .Values.services.ant.enabled }}
              - key: ant.conf
                path: ant.conf.template
              {{ end }}
              {{ if .Values.services.appfusion.enabled }}
              - key: appfusion.conf
                path: appfusion.conf.template
              {{ end }}
              {{ if .Values.services.codium.enabled }}
              - key: codium.conf
                path: codium.conf.template
              {{ end }}
              {{ if .Values.services.chromium.enabled }}
              - key: chromium.conf
                path: chromium.conf.template
              {{ end }}
              {{ if .Values.services.dbgate.enabled }}
              - key: dbgate.conf
                path: dbgate.conf.template
              {{ end }}
              {{ if .Values.services.ollama.enabled }}
              - key: ollama.conf
                path: ollama.conf.template
              {{ end }}
              {{ if (index .Values.services "open-webui").enabled }}
              - key: open-webui.conf
                path: open-webui.conf.template
              {{ end }}
              {{ if .Values.services.openclaw.enabled }}
              - key: openclaw.conf
                path: openclaw.conf.template
              {{ end }}
              {{ if .Values.services.opencode.enabled }}
              - key: opencode.conf
                path: opencode.conf.template
              {{ end }}
              {{ if .Values.services.openhands.enabled }}
              - key: openhands.conf
                path: openhands.conf.template
              {{ end }}
              {{ if (index .Values.services "redis-insight").enabled }}
              - key: redis-insight.conf
                path: redis-insight.conf.template
              {{ end }}
              {{ if (index .Values.services "scalar").enabled }}
              - key: scalar.conf
                path: scalar.conf.template
              {{ end }}

        - name: {{ .Release.Name }}-gateway-nginx
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-gateway-nginx

        - name: sshd.sock
          hostPath:
            path: /run/user/1000/gcr/ssh
            type: Socket
{{ end }}
