{{ if .Values.services.ollama.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ollama
  labels:
    app: {{ .Release.Name }}-ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ollama
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ollama
    spec:
      initContainers: 
        - name: pull
          image: {{ .Values.services.ollama.image }}
          imagePullPolicy: {{ .Values.deployments.containers.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              ollama serve &
              until ollama list >/dev/null 2>&1; do
                sleep 1
              done
              ollama pull gemma4:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: {{ .Release.Name }}-ollama-ollama
              mountPath: /root/.ollama
      containers:
        - name: server
          image: {{ .Values.services.ollama.image }}
          imagePullPolicy: {{ .Values.deployments.containers.pullPolicy }}
          env:
            # - name: OLLAMA_VULKAN
            #   value: true
          # Required for GPU passthrough
          securityContext:
            privileged: true
          volumeMounts:
            - name: {{ .Release.Name }}-ollama-ollama
              mountPath: /root/.ollama
          resources:
            limits:
              amd.com/gpu: 1 # requesting 1 GPU
      volumes:
        - name: {{ .Release.Name }}-ollama-ollama
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-ollama-ollama
{{ end }}
