{{ if has "opencode" .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-opencode
  labels:
    app: {{ .Release.Name }}-opencode
spec:
  {{ if .Values.devmode }}
  strategy:
    type: Recreate
  {{ end }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-opencode
  template:
    metadata:
      annotations:
      labels:
        app: {{ .Release.Name }}-opencode
        deployment: {{ .Release.Name }}-opencode
    spec:
      {{ include "pod.securityContext" . | indent 6 }}
      initContainers:
        - name: mkdir
          {{ include "container.securityContext" . | indent 10 }}
          image: docker.io/busybox:latest
          command: ["/bin/mkdir"]
          args: ["-p",
            "/mnt/{{ .Release.Name }}-opencode-opencode/.local",
            "/mnt/{{ .Release.Name }}-opencode-opencode/.cache",
            "/mnt/{{ .Release.Name }}-opencode-opencode/.config",
          ]
          volumeMounts:
            - name: {{ .Release.Name }}-opencode-opencode
              mountPath: /mnt/{{ .Release.Name }}-opencode-opencode
      containers:
        - name: server
          {{ include "container.securityContext" . | indent 10 }}
          image: localhost/core:latest
          imagePullPolicy: {{ .Values.deployments.containers.pullPolicy }}
          command: ["tini", "--"]
          args: ["bunx", "opencode", "serve", "--hostname", "0.0.0.0", "--port", "3000"]
          volumeMounts:
            - name: {{ .Release.Name }}-opencode-opencode
              mountPath: /home/core/.local
              subPath: .local
            - name: {{ .Release.Name }}-opencode-opencode
              mountPath: /home/core/.cache
              subPath: .cache
            - name: {{ .Release.Name }}-opencode-opencode
              mountPath: /home/core/.config
              subPath: .config

            {{ range .Values.deployments.volumes }}
            - name: {{ . }}
              mountPath: /home/core/workspace/{{ . }}
            {{ end }}

            - name: {{ .Release.Name }}-opencode-configmaps
              mountPath: /home/core/.config/opencode/opencode.json
              subPath: opencode.json

            - name: {{ .Release.Name }}-opencode-secrets
              mountPath: /home/core/.codex/auth.json
              subPath: auth.json

          livenessProbe:
            httpGet:
              path: /global/health
              port: 3000
          readinessProbe:
            httpGet:
              path: /global/health
              port: 3000

      volumes:
        - name: {{ .Release.Name }}-opencode-secrets
          secret:
            secretName: {{ .Release.Name }}-opencode
            optional: true
        - name: {{ .Release.Name }}-opencode-configmaps
          configMap:
            name: {{ .Release.Name }}-opencode
            optional: true

        - name: {{ .Release.Name }}-opencode-opencode
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-opencode-opencode

        {{ range .Values.deployments.volumes }}
        - name: {{ . }}
          persistentVolumeClaim:
            claimName: {{ . }}
        {{ end }}
{{ end }}