{{ if .Values.services.opencode.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-opencode
  labels:
    app: {{ .Release.Name }}-opencode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-opencode
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-opencode
    spec:
      {{ include "pod.securityContext" . | indent 6 }}
      initContainers:
        - name: mkdir
          {{ include "container.securityContext" . | indent 10 }}
          image: docker.io/busybox:latest
          command: ["/bin/mkdir"]
          args: ["-p",
            "/mnt/{{ .Release.Name }}-opencode-opencode/.local",
            "/mnt/{{ .Release.Name }}-opencode-opencode/.cache",
            "/mnt/{{ .Release.Name }}-opencode-opencode/.config",
          ]
          volumeMounts:
            - name: {{ .Release.Name }}-opencode-opencode
              mountPath: /mnt/{{ .Release.Name }}-opencode-opencode
      containers:
        - name: server
          {{ include "container.securityContext" . | indent 10 }}
          image: {{ .Values.services.opencode.image }}
          imagePullPolicy: {{ .Values.deployments.containers.pullPolicy }}
          command: ["tini", "--"]
          args: ["bunx", "opencode", "serve", "--hostname", "0.0.0.0", "--port", "3000"]
          env:
            - name: CONTAINER_HOST
              value: unix:///run/podman.sock
          volumeMounts:
            - name: {{ .Release.Name }}-opencode-opencode
              mountPath: /home/core/.local
              subPath: .local
            - name: {{ .Release.Name }}-opencode-opencode
              mountPath: /home/core/.cache
              subPath: .cache
            - name: {{ .Release.Name }}-opencode-opencode
              mountPath: /home/core/.config
              subPath: .config

            - name: {{ .Release.Name }}-opencode-configmaps
              mountPath: /home/core/.gitconfig
              subPath: .gitconfig
              readOnly: true
            - name: {{ .Release.Name }}-opencode-configmaps
              mountPath: /home/core/.config/opencode/opencode.json
              subPath: opencode.json

            {{ range .Values.deployments.volumes }}
            - name: {{ . }}
              mountPath: /home/core/workspace/{{ . }}
            {{ end }}
            {{ range .Values.deployments.volumeMounts }}
            - name: {{ .name }}
              mountPath: /home/core/workspace/{{ .name }}
            {{ end }}

            - name: podman.sock
              mountPath: /run/podman.sock

        - name: chrome-devtools-tunnel
          {{ include "container.securityContext" . | indent 10 }}
          image: docker.io/jnovack/autossh:latest
          env:
            - name: SSH_AUTH_SOCK
              value: /run/sshd.sock
          command:
            - autossh
            - "-M"
            - "0"
            - "-N"
            - "-o"
            - "UserKnownHostsFile=/dev/null"
            - "-o"
            - "StrictHostKeyChecking=no"
            - "-L"
            - "0.0.0.0:9222:127.0.0.1:9222"
            - "alexstorm13@host.containers.internal"

          volumeMounts:
            - name: sshd.sock
              mountPath: /run/sshd.sock
              readOnly: true

      volumes:
        - name: {{ .Release.Name }}-opencode-secrets
          secret:
            secretName: {{ .Release.Name }}-opencode
            optional: true
        - name: {{ .Release.Name }}-opencode-configmaps
          configMap:
            name: {{ .Release.Name }}-opencode
            optional: true

        - name: {{ .Release.Name }}-opencode-opencode
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-opencode-opencode

        {{ range .Values.deployments.volumes }}
        - name: {{ . }}
          persistentVolumeClaim:
            claimName: {{ . }}
        {{ end }}
        {{ range .Values.deployments.volumeMounts }}
        - name: {{ .name }}
          hostPath:
            path: {{ .mountPath }}
            type: Directory
        {{ end }}

        - name: podman.sock
          hostPath:
            path: /run/user/1000/podman/podman.sock
            type: Socket
        - name: sshd.sock
          hostPath:
            path: /run/user/1000/gcr/ssh
            type: Socket
{{ end }}
