{{ if (index .Values.services "redis-insight").enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-insight
  labels:
    app: {{ .Release.Name }}-redis-insight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis-insight
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis-insight
    spec:
      {{ include "pod.securityContext" . | indent 6 }}
      initContainers:
        - name: volume
          image: docker.io/busybox:latest
          command: ["/bin/mkdir"]
          args: ["-p",
            "/mnt/{{ .Release.Name }}-redis-insight/data",
          ]
          volumeMounts:
            - name: {{ .Release.Name }}-redis-insight
              mountPath: /mnt/{{ .Release.Name }}-redis-insight
      containers:
        - name: redis-insight
          {{ include "container.securityContext" . | indent 10 }}
          image: {{ (index .Values.services "redis-insight").image }}
          imagePullPolicy: {{ .Values.deployments.containers.pullPolicy }}
          volumeMounts:
            - name: {{ .Release.Name }}-redis-insight
              mountPath: /data
              subPath: data
      volumes:
        - name: {{ .Release.Name }}-redis-insight
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-redis-insight
{{ end }}
